---
# tasks file for roles/api_compose
- name: Ensure the project directory exists.
  ansible.builtin.file:
    path: "{{ api_compose_dir }}"
    state: directory
    mode: "0755"
- name: Look for existing compose
  ansible.builtin.stat:
    path: "{{ api_compose_dir }}/docker-compose.yaml"
  register: compose_stat
- name: Tear down existing services
  community.docker.docker_compose_v2:
    project_src: "{{ api_compose_dir }}"
    state: absent
  when: compose_stat.exists is defined and compose_stat.exists
- name: Create compose project
  ansible.builtin.template:
    src: templates/docker-compose.yaml.j2
    dest: "{{ api_compose_dir }}/docker-compose.yaml"
- name: Create conf file
  ansible.builtin.template:
    src: templates/dev.conf.j2
    dest: "{{ api_compose_dir }}/dev.conf"
